/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  CategoryEnum: "Art" | "Books" | "Comics" | "Computers" | "Film" | "Games" | "General Knowledge" | "Geography" | "History" | "Mathematics" | "Music" | "Mythology" | "Nature" | "Politics" | "Sports" | "Television"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Mutation: {};
  Query: {};
  Question: { // root type
    category?: NexusGenEnums['CategoryEnum'] | null; // CategoryEnum
    correct_answer: string; // String!
    difficulty: string; // String!
    hint?: string | null; // String
    id: number; // Int!
    question_content: string; // String!
    wrong_answers?: string[] | null; // [String!]
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    post: NexusGenRootTypes['Question']; // Question!
  }
  Query: { // field return type
    feed: NexusGenRootTypes['Question'][]; // [Question!]!
  }
  Question: { // field return type
    category: NexusGenEnums['CategoryEnum'] | null; // CategoryEnum
    correct_answer: string; // String!
    difficulty: string; // String!
    hint: string | null; // String
    id: number; // Int!
    question_content: string; // String!
    wrong_answers: string[] | null; // [String!]
  }
}

export interface NexusGenFieldTypeNames {
  Mutation: { // field return type name
    post: 'Question'
  }
  Query: { // field return type name
    feed: 'Question'
  }
  Question: { // field return type name
    category: 'CategoryEnum'
    correct_answer: 'String'
    difficulty: 'String'
    hint: 'String'
    id: 'Int'
    question_content: 'String'
    wrong_answers: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    post: { // args
      category: string; // String!
      correct_answer: string; // String!
      difficulty: string; // String!
      hint?: string | null; // String
      question_content: string; // String!
      wrong_answers: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}